version: "3.9"
services:
  app:
    build: ./hostnameapp/hostnameapp
    expose: 
      - "5000"    
      
  app2:
    build: ./hostnameapp/host2
    expose: 
      - "5010"     
  proxy:
    #image: nginx:alpine
    build: ./nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app  
      - app2  
    links:
      - app  
      - app2  
    ports:
      - "8082:80"